# Generated by Django 3.2.3 on 2021-06-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_line1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='line1',
            new_name='author',
        ),
    ]
