# Generated by Django 3.2.3 on 2021-06-21 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_line1_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feild',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
