# Generated by Django 3.2.3 on 2021-06-22 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210621_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentt', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
