# Generated by Django 3.2.3 on 2021-06-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
    ]
