# Generated by Django 3.2.3 on 2021-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='name',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
